import React, { useRef } from "react";
import Head from "next/head";
import ButtonNavigation from "../components/button-navigation/button-navigation";

import styles from "../styles/Home.module.css";
import classes from "./home.module.css";
import OrderOnlineButton from "../components/order-online-button/order-online-button";
import { GetStaticProps } from "next";
import { gql } from "@apollo/client";
import client from "../lib/apollo";

type Props = {
  data: any;
};

const HomePage = ({ data }: Props) => {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>EZ Eats</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <OrderOnlineButton />
      <div className={classes.grid_container}>
        {data &&
          data.allHomePage.map((content: any) => {
            return (
              <ButtonNavigation
                content={content.tile_name.replace("-", "\n")}
                img={content.tile_icon.asset.url}
                img2={content.tile_image.asset.url}
                path={content.slug.current}
              />
            );
          })}
      </div>
      <OrderOnlineButton />
    </div>
  );
};

export default HomePage;

const GET_HOME = gql`
  {
    allHomePage(sort: { tile_number: ASC }) {
      _id
      tile_number
      tile_name
      tile_image {
        asset {
          url
        }
      }
      tile_icon {
        asset {
          url
        }
      }
      slug {
        current
      }
    }
  }
`;

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const results = await client.query({
    query: GET_HOME,
  });
  if (!results) {
    return { notFound: true };
  }

  return {
    props: {
      data: results.data,
    },
    revalidate: 600,
  };
};
