import React, { useRef } from "react";
import Head from "next/head";
import ButtonNavigation from "../components/button-navigation/button-navigation";

import styles from "../styles/Home.module.css";
import classes from "./home.module.css";

type Props = {};

const HomePage = (props: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>EZ Eats</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className={classes.grid_container}>
        <ButtonNavigation
          content="Trailers & \n Food Tents"
          img={"/img/foodtrailer.png"}
          img2={"/img/quesadilla.jpg"}
          path="/trailer"
        />
        <ButtonNavigation
          content="Beer & \n Wine Dinners"
          img={"/img/beer-wine.png"}
          img2={"/img/kolache.jpg"}
          path="/beer-wine"
        />
        <ButtonNavigation
          content="EZ Eats \n Kitchen"
          img={"/img/catering.png"}
          img2={"/img/tacos.jpg"}
          path="/ez-eats-kitchen"
        />
        <ButtonNavigation
          content="Meal Prep"
          img={"/img/meal-prep.png"}
          img2={"/img/cookies.jpg"}
          path="/meal-prep"
        />
      </div>
    </div>
  );
};

export default HomePage;
